### PR TITLE
Replaced Deprecated Parameter `role_arn`

### PR DESCRIPTION
**Pull request by milldr**
## what
- Replaced `role_arn` with `assume_role.role_arn` for `remote-state` module

## why
- The AWS provider has deprecated `role_arn` and suggests replacing with `assume_role.role_arn`

## references
image

### CODE REVIEW

**Comment by hans-d** [comment]
@milldr can you redo the readme ?

**Comment by hans-d** [comment]
@milldr Given the failures in the terratest, can you chek if that might be related to the chnage you have done? Will do some checks as wel, but that might take a bit more time.

**Comment by milldr** [comment]
@hans-d I believe these checks are related to the Spacelift module, which may be failing because we don't have a test Spacelift organization set up. We may need to fix the tests themselves. They're also failing for the README-only change with #73

**Comment by hans-d** [comment]
Added that to the list of other tests needing fixing. Can you poke some of the team to get the merge done with an override ?

**Comment by milldr** [comment]
yeah, no problem. I'll raise this PR internally

**Comment by milldr** [comment]
additional work is required for this change. 

The team is reluctant to re-arrange the AWS provider block as that is a sweeping change that affects all our `provider.tf` files and possibly the way we manage that configuration in atmos, and for so little benefit that we remain hopeful that AWS will reverse course on the change

**Comment by Nuru** [comment]
@milldr This was fixed by #105, released in v1.8.0

**Pull request closed without merging**
