### PR TITLE
Update to new `null-label`. Add `stack` sub-module to calculate stack names

### PR DESCRIPTION
**Pull request by aknysh**
## what
* Update to new `null-label`
* Add `stack` sub-module to calculate stack names

## why
* Use new features from `null-label` module:
  - Additional label and `id` component: `tenant`
  - New input `labels_as_tags` controls which labels are exported as tags  
  - New input `descriptor_formats` generates new output `descriptors` - use it to calculate the stack names

*  `stack` submodule is used to calculate stack names in one place and use the same logic in all other sub-modules

## references
* https://github.com/cloudposse/terraform-null-label/pull/132

### CODE REVIEW

**Review by osterman — APPROVED** [review]

**Review by osterman — APPROVED** [review]

**Review by Nuru — APPROVED** [review]

**Review by korenyoni — APPROVED** [review]
Looks good to me. 

One thing I will say is I think `context-always` should be exported from `null_label` and automated via the `auto-context` workflow, but perhaps renamed to `context-stack-config` so that it isn't used anywhere else. Either way, that's not really relevant to this PR and can be done later if anyone shares my opinion.

**Pull request merged**
